2024-05-07 21:40:24,755 ERROR: Unhandled exception [in /home/rzu/microblog/app/tasks.py:54]
Traceback (most recent call last):
  File "/home/rzu/microblog/app/tasks.py", line 44, in export_posts
    send_email(
  File "/home/rzu/microblog/app/email.py", line 25, in send_email
    mail.send(msg)
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 158, in configure_host
    host = smtplib.SMTP(self.mail.server, self.mail.port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
2024-05-07 21:43:41,378 INFO: Microblog startup [in /home/rzu/microblog/app/__init__.py:91]
2024-05-07 21:44:18,664 ERROR: Unhandled exception [in /home/rzu/microblog/app/tasks.py:54]
Traceback (most recent call last):
  File "/home/rzu/microblog/app/tasks.py", line 44, in export_posts
    send_email(
  File "/home/rzu/microblog/app/email.py", line 25, in send_email
    mail.send(msg)
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rzu/.local/share/virtualenvs/microblog-oeRwd4YA/lib/python3.11/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/home/rzu/.pyenv/versions/3.11.9/lib/python3.11/smtplib.py", line 716, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
2024-05-07 21:57:43,964 INFO: Microblog startup [in /home/rzu/microblog/app/__init__.py:91]
